name: atcoder
version: 0.1.0.0
github: cohei/atcoder
license: BSD3
author: TANIGUCHI Kohei
maintainer: a.d.xvii.kal.mai@gmail.com
copyright: 2018 TANIGUCHI Kohei

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/cohei/atcoder#readme>

ghc-options:
  - -Wall

dependencies:
  - base >= 4.7 && < 5
  - array
  - bytestring
  - containers
  - hspec
  - main-tester
  - mtl

library:
  source-dirs: src

tests:
  ABC112:
    main: test/AtCoderBeginnerContest112.hs
    dependencies:
      - atcoder
  AGC028:
    main: test/AtCoderGrandContest028.hs
    dependencies:
      - atcoder
      - heredoc
  Tenka1:
    main: test/Tenka1ProgrammerBeginnerContest.hs
    dependencies:
      - atcoder
      - heredoc
  ABC113:
    main: test/AtCoderBeginnerContest113.hs
    dependencies:
      - atcoder
      - heredoc
  Dwango5:
    main: test/DwangoProgrammingContestV.hs
    dependencies:
      - atcoder
      - heredoc

executables:
  ABC024-A:
    source-dirs: app/AtCoderBeginnerContest024
    main: a.hs
  ABC024-B:
    source-dirs: app/AtCoderBeginnerContest024
    main: b.hs
  ABC030-A:
    source-dirs: app/AtCoderBeginnerContest030
    main: a.hs
  ABC030-B:
    source-dirs: app/AtCoderBeginnerContest030
    main: b.hs
  ABC030-C:
    source-dirs: app/AtCoderBeginnerContest030
    main: c.hs
  AGC014-A:
    source-dirs: app/AtCoderGrandContest014
    main: a.hs
  AGC014-F:
    source-dirs: app/AtCoderGrandContest014
    main: f.hs
  ARC028-A:
    source-dirs: app/AtCoderRegularContest028
    main: a.hs
  ARC028-B:
    source-dirs: app/AtCoderRegularContest028
    main: b.hs
  ARC045-A:
    source-dirs: app/AtCoderRegularContest045
    main: a.hs
  ARC045-B:
    source-dirs: app/AtCoderRegularContest045
    main: b.hs
  AGC026-A:
    source-dirs: app/AtCoderGrandContest026
    main: a.hs
  AGC026-B:
    source-dirs: app/AtCoderGrandContest026
    main: b.hs
  AGC026-C:
    source-dirs: app/AtCoderGrandContest026
    main: c.hs
  ABC104-A:
    source-dirs: app/AtCoderBeginnerContest104
    main: a.hs
  ABC104-B:
    source-dirs: app/AtCoderBeginnerContest104
    main: b.hs
  ABC105-A:
    source-dirs: app/AtCoderBeginnerContest105
    main: a.hs
  ABC105-B:
    source-dirs: app/AtCoderBeginnerContest105
    main: b.hs
  ABC105-C:
    source-dirs: app/AtCoderBeginnerContest105
    main: c.hs
  ABC105-D:
    source-dirs: app/AtCoderBeginnerContest105
    main: d.hs
  ABC110-A:
    source-dirs: app/AtCoderBeginnerContest110
    main: a.hs
  ABC110-B:
    source-dirs: app/AtCoderBeginnerContest110
    main: b.hs
  ABC110-C:
    source-dirs: app/AtCoderBeginnerContest110
    main: c.hs
  ABC110-D:
    source-dirs: app/AtCoderBeginnerContest110
    main: d.hs
