name: atcoder
version: 0.1.0.0
github: cohei/atcoder
license: BSD3
author: TANIGUCHI Kohei
maintainer: a.d.xvii.kal.mai@gmail.com
copyright: 2018 TANIGUCHI Kohei

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/cohei/atcoder#readme>

ghc-options:
  - -optc-Wno-expansion-to-defined
  - -Wall
  - -fdefer-typed-holes

dependencies:
  - base >= 4.7 && < 5
  - array
  - bytestring
  - containers
  - hspec
  - main-tester
  - mtl

library:
  source-dirs: src

tests:
  ABC112:
    main: test/AtCoderBeginnerContest112.hs
    dependencies:
      - atcoder
  AGC028:
    main: test/AtCoderGrandContest028.hs
    dependencies:
      - atcoder
      - heredoc
  Tenka1:
    main: test/Tenka1ProgrammerBeginnerContest.hs
    dependencies:
      - atcoder
      - heredoc
  ABC113:
    main: test/AtCoderBeginnerContest113.hs
    dependencies:
      - atcoder
      - heredoc
  Dwango5:
    main: test/DwangoProgrammingContestV.hs
    dependencies:
      - atcoder
      - heredoc
  ABC117:
    main: test/AtCoderBeginnerContest117.hs
    dependencies:
      - atcoder
      - heredoc
