name: atcoder
version: 0.1.0.0
github: cohei/atcoder
license: BSD3
author: TANIGUCHI Kohei
maintainer: a.d.xvii.kal.mai@gmail.com
copyright: 2018 TANIGUCHI Kohei

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/cohei/atcoder#readme>

ghc-options:
  - -optc-Wno-expansion-to-defined
  - -Wall
  - -fdefer-typed-holes

  # https://downloads.haskell.org/~ghc/7.10.3/docs/html/users_guide/options-sanity.html
  # The warnings that are not enabled by `-Wall`
  - -fwarn-auto-orphans
  - -fwarn-identities
  - -fwarn-incomplete-record-updates
  - -fwarn-incomplete-uni-patterns
  - -fwarn-missing-exported-sigs
  - -fwarn-missing-import-lists
  - -fwarn-missing-local-sigs
  - -fwarn-monomorphism-restriction

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - array
    - containers
    - mtl
    - time
    - vector

tests:
  atcoder-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - atcoder
      - bytestring
      - heredoc
      - hspec
      - main-tester
    build-tools:
      - hspec-discover
