name: atcoder
version: 0.1.0.0
license: BSD3

library:
  source-dirs: src
  dependencies:
    - base
    - bytestring
    - containers
    - mtl
    - parsec
    - time
    - vector

tests:
  atcoder-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - base
      - atcoder
      - bytestring
      - heredoc
      - hspec
      - main-tester
    build-tools:
      - hspec-discover
